name: login_app
description: A Flutter app with Supabase authentication for phone/email login

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.0
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  http: ^1.1.0
  mailer: ^6.0.1
  geolocator: ^10.1.0
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  record: ^5.0.4
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

